name: Use GitHub Models

on:
  workflow_dispatch:
    inputs:
      round:
        description: Race round number
        required: true
        type: string
      date:
        description: Race date
        required: true
        type: string  
      qualifications_a_member_id:
        description: 'Qualifications A member_id'
        required: true
        type: string
      race_a_member_id:
        description: 'Race A member_id'
        required: true
        type: string
      qualifications_b_member_id:
        description: 'Qualifications B member_id'
        required: true
        type: string
      race_b_member_id:
        description: 'Race B member_id'
        required: true
        type: string

permissions:
  models: read
  contents: write
  issues: write

jobs:
  call-model:
    runs-on: ubuntu-latest
    steps:
      - name: Call AI model
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ROUND: ${{ inputs.round }}
          RACE_DATE: ${{ inputs.date }}
          QUALIFICATIONS_A: ${{ inputs.qualifications_a_member_id }}
          RACE_A: ${{ inputs.race_a_member_id }}
          QUALIFICATIONS_B: ${{ inputs.qualifications_b_member_id }}
          RACE_B: ${{ inputs.race_b_member_id }}
        run: |
          curl "https://models.github.ai/inference/chat/completions" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer $GITHUB_TOKEN" \
             -d '{
              "messages": [
                  {
                     "role": "user",
                     "content": "Explain the concept of recursion."
                  }
               ],
               "model": "openai/gpt-4o"
            }'
